#!/system/bin/sh
# POST boot.img → extract zImage+ramdisk+DTB, load kexec, execute
# Content-Type of request should be application/octet-stream (raw boot.img)
echo "Content-Type: text/plain"
echo ""

BB=/sbin/busybox
TMP=/data/local/tmp/kexec_work
KEXEC=/sbin/kexec

rm -rf $TMP && mkdir -p $TMP

# Save uploaded boot.img
$BB cat > $TMP/boot.img

# Parse header
KS=$($BB od -A n -t u4 -j 8 -N 4 $TMP/boot.img | $BB tr -d " ")
RS=$($BB od -A n -t u4 -j 16 -N 4 $TMP/boot.img | $BB tr -d " ")
SS=$($BB od -A n -t u4 -j 24 -N 4 $TMP/boot.img | $BB tr -d " ")
PS=$($BB od -A n -t u4 -j 36 -N 4 $TMP/boot.img | $BB tr -d " ")
DS=$($BB od -A n -t u4 -j 40 -N 4 $TMP/boot.img | $BB tr -d " ")

KP=$(( (KS + PS - 1) / PS * PS ))
RP=$(( (RS + PS - 1) / PS * PS ))
SP=$(( (SS + PS - 1) / PS * PS ))
RO=$(( PS + KP ))
SO=$(( RO + RP ))
DO=$(( SO + SP ))

# Extract components
dd if=$TMP/boot.img bs=$PS skip=1 count=$((KP/PS)) of=$TMP/zImage 2>/dev/null
$BB truncate -s $KS $TMP/zImage
dd if=$TMP/boot.img bs=$PS skip=$((RO/PS)) count=$((RP/PS)) of=$TMP/initrd.img 2>/dev/null
$BB truncate -s $RS $TMP/initrd.img
if [ "$DS" -gt 0 ]; then
    dd if=$TMP/boot.img bs=$PS skip=$((DO/PS)) count=$(((DS+PS-1)/PS)) of=$TMP/dtb.img 2>/dev/null
    $BB truncate -s $DS $TMP/dtb.img
fi

echo "zImage=$KS ramdisk=$RS dtb=$DS"

# Get cmdline
CMDLINE=$(cat /proc/cmdline)

# Build kexec command
KCMD="$KEXEC --load-hardboot --mem-min=0x85000000 --mem-max=0xd0000000 --boardname=mocha"
KCMD="$KCMD --initrd=$TMP/initrd.img"
[ "$DS" -gt 0 ] && KCMD="$KCMD --dtb=$TMP/dtb.img"
KCMD="$KCMD --append=\"$CMDLINE\""
KCMD="$KCMD $TMP/zImage"

# Load
eval $KCMD 2>&1

# Execute (in background, send response first)
echo "KEXEC_LOADED"
$KEXEC -e </dev/null >/dev/null 2>&1 &
